### ISSUE TITLE
我喜欢你

### ISSUE THREAD

**Issue by notch1p** [yyym-y/yyym-y.github.io#1]
把你加到友链里了。但是有点[小问题](https://www.notion.so/bermbob/Atelier-Evan-136ad01183e24e67b8132aca9616407b?pvs=4#cb2b708651ee4479a06077f5e8d4f4e2)，如图：
<img width="814" alt="image" src="https://github.com/yyym-y/yyym-y.github.io/assets/18750154/ce8c1bbc-5016-40ec-8611-23fabb0334c6">
可以给页面加一点metadata，这样也方便搜索引擎索引。

**Comment by notch1p** [comment]
Also chjeck [this page](https://aikoyori.xyz/) as this person also loves bocchi just like you.

**Comment by yyym-y** [comment]
> 把你加到友链里了。但是有点[小问题](https://www.notion.so/bermbob/Atelier-Evan-136ad01183e24e67b8132aca9616407b?pvs=4#cb2b708651ee4479a06077f5e8d4f4e2)，如图： <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/18750154/323557429-ce8c1bbc-5016-40ec-8611-23fabb0334c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTEwOTQsIm5iZiI6MTcxMzc1MDc5NCwicGF0aCI6Ii8xODc1MDE1NC8zMjM1NTc0MjktY2U4YzFiYmMtNTAxNi00MGVjLTg2MTEtMjNmYWJiMDMzNGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MjFhOGQ2MzZmZWQ2NmJjZmQzZmUxYzM4YmI4NTMwMzA4NjdkNDMwZjViNmZiNDFjMzBjNmFlOTY3MzE2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZNu_p_d_ZmNLw_ggIR1VHLOyr4Y9ibqc4TxOCW7qvNw"> 可以给页面加一点metadata，这样也方便搜索引擎索引。

前几天都没有上github, 昨天才看到, 已经把 mate 标签更新了
另外 : 你的 blog 好像几百年没更新了 (*＞◡❛)
死南通能不能滚啊 ꍞ(:˒[▓︎▓︎]

**Comment by yyym-y** [comment]
> Also chjeck [this page](https://aikoyori.xyz/) as this person also loves bocchi just like you.

这是我们学校同学的网站麽

**Comment by notch1p** [comment]
不是 网上看见的。我觉得他的主页设计得很炫酷

On Apr 22, 2024, at 09:59, yyym ***@***.***> wrote:



Also chjeck this page<https://aikoyori.xyz/> as this person also loves bocchi just like you.

这是我们学校同学的网站麽

**Comment by yyym-y** [comment]
> 把你加到友链里了。但是有点[小问题](https://www.notion.so/bermbob/Atelier-Evan-136ad01183e24e67b8132aca9616407b?pvs=4#cb2b708651ee4479a06077f5e8d4f4e2)，如图： <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/18750154/323557429-ce8c1bbc-5016-40ec-8611-23fabb0334c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjY3MDcsIm5iZiI6MTcxMzc2NjQwNywicGF0aCI6Ii8xODc1MDE1NC8zMjM1NTc0MjktY2U4YzFiYmMtNTAxNi00MGVjLTg2MTEtMjNmYWJiMDMzNGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA2MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDA3OTU5MTdkODE4NGMxNTY1ZmY5MzZlMDg3OTYzOGY1YjdkOThhYTIzYmQ1YmVjYTI1NDdiZmZlZjQxNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFDl3NG37_9BI9x6s6xZSYvdWO7xnQh2WJowgo_phkk"> 可以给页面加一点metadata，这样也方便搜索引擎索引。

回去看了下, 改了mate,但是你的网站上好像还是没有改过来, 不懂....
好像你那不是动态更新的...

**Comment by notch1p** [comment]
我的博客后端是Notion. Notion本身不会自动更新网站书签，所以我博客从Notion API拉取的时候也不会更新。我去Notion手动刷新了一下，现在应该正常了。

**Comment by yyym-y** [comment]
> 我的博客后端是Notion. Notion本身不会自动更新网站书签，所以我博客从Notion API拉取的时候也不会更新。我去Notion手动刷新了一下，现在应该正常了。

![image](https://github.com/yyym-y/yyym-y.github.io/assets/133961507/cb6a12f8-3a66-471e-b2be-6b794aa5b21b)
